### ISSUE TITLE
Long polling support for CORS

### ISSUE THREAD

**Issue by lostcolony** [ninenines/bullet#18]
Currently Bullet offers no cross origin support for the long polling fallback. I'm not sure it makes sense to add this (all browsers other than IE have supported websockets for the past 9 months, and IE 10 supports it natively so it's only a matter of time before it is made obsolete), but adding it would not be hard, and it seems like it could be an interesting WTF for a developer in the mean time if they were lackadaisical in testing the long polling fallback in a cross domain context.

Adding it would not be difficult, however, to what extent user participation should be required would need to be decided upon.

Essentially, the bullet_handler would need to accept an "OPTIONS" request, that returns a response with the header "Access-Control-Allow-Origin", and the domain(s) to allow as the value, as well as a "Access-Control-Allow-Headers" with the headers the response needs as declared in the request header "Access-Control-Request-Headers" (by default; it might also make sense to allow the user to configure this should they need to). The "Access-Control-Allow-Origin" header would need to be supplied for the POST as well.

I'd not be averse to taking a stab at implementing this on a fork, but it begs the question, A. What should the interface look like, and B. Should restricting the allowed domains also be included as part of the websocket connection? I.e., the handler to supply to Bullet has an optional function to declare the allowed domains, otherwise it defaults to all. Then use that for the CORS header value in case of long polling, as well as check against it before allowing a websocket connection to be opened.

**Comment by essen** [comment]
Closing, thanks!
