### ISSUE TITLE
erlang / utf / bullet

### ISSUE THREAD

**Issue by txrev319** [ninenines/bullet#56]
When using https://raw.github.com/extend/bullet/master/src/bullet_handler.erl

I get an error of:

src/bullet_handler.erl:5: cannot parse file, giving up
src/bullet_handler.erl:5: cannot translate from UTF-8

(I reordered the lines so that it looked like:

-module(bullet_handler).
-behaviour(cowboy_http_handler).
-behaviour(cowboy_websocket_handler).

%% Copyright (c) 2011-2012, Loic Hoguin essen@ninenines.eu
%%
%% Permission to use, copy, modify, and/or distribute this software for any
%% purpose with or without fee is hereby granted, provided that the above
%% copyright notice and this permission notice appear in all copies.

)

Anyway, the problem is that erlang (r17-rc2 on Ubuntu 64) seems to
dislike the "   ï   " in Loic, and changing it to "   i    " fixed it.

**Comment by barberj** [comment]
still occurs. in 18.0. I've submitted https://github.com/ninenines/bullet/pull/83 as a resolution
