### ISSUE TITLE
Would you consider replacing jquery with custom code or simple xhr package.

### ISSUE THREAD

**Issue by lud** [ninenines/bullet#64]
Bullet depends on JQuery only for $.ajax ...

You could use [SeXHR](https://github.com/skibz/SeXHR) (supports `async:true` OOTB) or even copy [microAjax](http://code.google.com/p/microajax/) inside your code and add sync support).

What do you think ?

**Comment by coolfeature** [comment]
I would welcome the change. jQuery is nice but if you are pedantic and you work with e.g. angular js which competes with jQuery you want libraries that do not depend on it...

**Comment by fgallaire** [comment]
+1 to remove jQuery

**Comment by essen** [comment]
All browsers have been supporting Websocket for a while. Most support eventsource as well (IE/Edge only via polyfills). I am therefore going to archive the Bullet project. Thanks everyone for using and contributing to this project!
