### ISSUE TITLE
No fallback for ERR_TUNNEL_CONNECTION_FAILED 

### ISSUE THREAD

**Issue by coolfeature** [ninenines/bullet#70]
I am getting:
WebSocket connection to 'ws://xxx.xxx.xxxx.xxxx:8000/path' failed: Error in connection establishment: net::ERR_TUNNEL_CONNECTION_FAILED 
on line 223:
var ret = new t.transport(url);

Would be nice if bullet detected the error and fell back onto xhr...

**Comment by essen** [comment]
I'm not even sure what browser you are using there, or what you're doing exactly. Can't help you with only that info.

**Comment by coolfeature** [comment]
I am using Version 40.0.2214.94 m and I am visiting a website from inside an organisation network so the request goes through a proxy that apparently does not line to tunnel ws connections...

**Comment by essen** [comment]
Still didn't say the browser. :-)

Anyway I don't have access to that kind of setup so I can't debug and fix. When connection with WS fails in all cases I've tested it then tries XHR, not sure why it wouldn't in this particular case.

**Comment by essen** [comment]
Also you might want to just use WSS as it shouldn't be able to reject it if it's encrypted.

**Comment by alopia** [comment]
**I don't think this is a bullet problem.** I encountered the same error on Google Chrome with a corporate proxy that is filtering content based on domain and IP blacklist.

SSL and particularly WSS does not fix the problem if the proxy is setup to deny access to a blacklist of domains and IP addresses.

How you can replicate this:
- It's happening on Windows 7
- Use (any) proxy server that can deny access to test.com domain or the domain IP.
- Request any URL including wss://test.com, ws://test.com, https://test.com or http://test.com
- the proxy will not connect to the requested domain and will respond with a 502 Bad Gateway or a 302 Found (depends on proxy implementation or configuration) and (depends on proxy) a custom body message explaining the access to that domain was denied by the proxy.

Google chrome will NOT show the proxy body message but instead will show something like this when the request was made using http/https:

This webpage is not available
The webpage at https://www.facebook.com/ might be temporarily down or it may have moved permanently to a new web address.
Error 111 (net::ERR_TUNNEL_CONNECTION_FAILED): Unknown error.

For ws and wss will trigger exactly that error (net::ERR_TUNNEL_CONNECTION_FAILED).

Notice that the same problem occure on Internet explorer but the error is diffrent. More about this you can read here: https://blogs.technet.microsoft.com/nettracer/2011/09/22/internet-explorer-doesnt-display-isa-or-tmg-error-message-502-when-connecting-to-https-servers/

**Comment by alopia** [comment]
**I don't think this is a bullet problem.** I encountered the same error on Google Chrome with a corporate proxy that is filtering content based on domain and IP blacklist.

SSL and particularly WSS does not fix the problem if the proxy is setup to deny access to a blacklist of domains and IP addresses.

**How you can replicate this:**
- It's happening on Windows 7 with ANY Google chrome version
- Use (any) proxy server that can deny access to test.com domain or the domain IP or a server emulating this proxy response (responding with 502 Bad Gateway header).
- Request any URL including wss://test.com, ws://test.com, https://test.com or http://test.com
- the proxy will not connect to the requested domain and will respond with a 502 Bad Gateway and (depends on proxy) a custom body message explaining the access to that domain was denied by the proxy.

Google chrome will NOT show the proxy body message but instead will show something like this when the request was made using http/https:

```
This webpage is not available
The webpage at https://test.com/ might be temporarily down or it may have moved permanently to a new web address.
Error 111 (net::ERR_TUNNEL_CONNECTION_FAILED): Unknown error.
```

Requesting ws and wss protocol will trigger exactly that error (net::ERR_TUNNEL_CONNECTION_FAILED).

**Notice that the same problem occurs on Internet explorer** but the response is different. More about this you can read here: https://blogs.technet.microsoft.com/nettracer/2011/09/22/internet-explorer-doesnt-display-isa-or-tmg-error-message-502-when-connecting-to-https-servers/

I suspect other browser may handle this situation different and there is no way bullet can distinguish between a normal Not found, Found or Bat Gateway and a proxy denying access to the host.

For example to make things worst some proxy responds with a 302 Found and a custom body message telling the user the access was denied to the specified host.

Trying other methods like long pooling will not solve the problem of proxy blocking access to the specified host no matter what protocol you use. In my opinion this should be deleted from the feature request.

**Comment by essen** [comment]
All browsers have been supporting Websocket for a while. Most support eventsource as well (IE/Edge only via polyfills). I am therefore going to archive the Bullet project. Thanks everyone for using and contributing to this project!
