### ISSUE TITLE
way to shutdown connection on info when using eventsource

### ISSUE THREAD

**Issue by marianoguerra** [ninenines/bullet#81]
when Handler:info is called and the message received requires to shutdown the connection it can be done on COMET (reply some empty thing), on websocket return shutdown https://github.com/ninenines/bullet/blob/master/src/bullet_handler.erl#L136 but not with eventsource (sse).

what I propose is to allow eventsource to reply shutdown and add a new case clause here https://github.com/ninenines/bullet/blob/master/src/bullet_handler.erl#L107 with 

    {shutdown, Req2, HandlerState2} when GetMode == eventsource -> {ok, Req2, State2}

it could also handle the case where GetMode == poll by replying 204.

will you accept the pull request? if so, only for eventsource or for poll too?
do you recommend an alternative way?

**Comment by essen** [comment]
Allowing a shutdown reply sounds most sensible.

**Comment by marianoguerra** [comment]
@essen what do you think about that commit? ^ should I just open a PR and discuss it there?

**Comment by essen** [comment]
Other than whitespace issue, it looks fine.

**Comment by essen** [comment]
If you want, and have time, you may send a single PR for all your changes (and possibly including changes from other people), and I can check it all at once and merge. Otherwise I don't know when I can look into these things.

**Comment by essen** [comment]
As long as it's still separate commits per issue it's fine.
