### ISSUE TITLE
[Suggestion] upgrade to use cowboy 2

### ISSUE THREAD

**Issue by beenotung** [ninenines/bullet#86]
I'm new to bullet, the demo is impressive.
However, when I try to plug in bullet into my project, I realise it is depending on cowboy 1, and erlang vm doesn't allow nested dependency like nodejs do (only flat dependecies). So, to gain the performance improvement from cowboy 2, I've to not use bullet for now.

**Comment by beenotung** [comment]
If there is no roadmap to do the upgrade, I'm happy to help.

**Comment by essen** [comment]
Been busy with other things so if you can send a PR that'd help!

**Comment by essen** [comment]
Still hoping for a PR!

**Comment by beenotung** [comment]
I made a project using cowboy2 but have some strong binding to encryptions.
Will extract the connection part then make a PR.
